# https://taskfile.dev

version: "3"

tasks:
  library:
    dir: library
    sources:
      - "**/*.ts"
      - "**/*.js"
      - "**/*.json"
    generates:
      - "dist/**/*"
      - "../bundles/*"
    cmds:
      - pnpm i
      - pnpm build
      - for:
          [
            "datastar-aliased.ts",
            "datastar-core.ts",
            "datastar.ts",
            "datastar-csp.ts",
            "datastar-aliased-csp.ts",
          ]
        cmd: |
          npx esbuild --bundle src/bundles/{{.ITEM}}  \
          --define:__USE_UPLOAD_PROGRESS__=true \
          --define:ALIAS=null \
          --outdir=../bundles/  \
          --minify --sourcemap \
          --target=es2023 \
          --format=esm

  test:
    dir: tests
    desc: Run the test suite against the standard and CSP bundles
    cmds:
      - for: ["datastar", "datastar-csp"]
        cmd: BUNDLE={{.ITEM}} pnpm playwright test

  default:
    deps: [library]
